#######################################################################################
# Book settings
title : Computação Gráfica 2020-2021
author: Margarida Madeira e Moura
logo: 'images/logo.png'

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : off

#######################################################################################
# HTML-specific settings
html:
  use_repository_button       : false
  home_page_in_navbar         : false
  baseurl                     : https://margaridamadeira.github.io/CGr-2020-21/

#######################################################################################

# Information about where the book exists on the web
repository:
  url                         : https://github.com/margaridamadeira/CGr-2020-21
  path_to_book                : docs  # Optional path to your book, relative to the repository root
  # branch                    : master  # Which branch of the repository should be used when creating links


# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

parse:
  myst_extended_syntax: true
